# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: check gepetuto

on: [push, pull_request]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Install gepetuto and its dependencies
      run: pipx install poetry && poetry install
    - name: check with gepetuto
      run: poetry run gepetuto -vvca all -C tests
    - name: run unit tests
      run: cd tests && poetry run python -m unittest
    - name: run mypy
      run: poetry run mypy --explicit-package-bases tests gepetuto
