name: check gepetuto

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    - name: Install gepetuto and its dependencies
      run: pipx install poetry && poetry install --with dev
    - name: check with gepetuto
      run: poetry run gepetuto -vvca all -C tests
    - name: run unit tests
      run: cd tests && poetry run python -m unittest
    - name: run mypy
      run: poetry run mypy --explicit-package-bases tests gepetuto
